### ISSUE TITLE
Crash when connected to new monitor

### ISSUE THREAD

**Issue by 1995parham** [danyspin97/wpaperd#10]
`wpaperd` crashes when new monitor connects.

**Comment by danyspin97** [comment]
Can you please share the log file when wpaperd crashes?  You can find it inside `.local/state/wpaperd/`.

**Comment by 1995parham** [comment]
```
The application panicked (crashed).                                                                                                                                                                         
Message:  already borrowed: BorrowMutError
Location: src/main.rs:233

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by 1995parham** [comment]
I think we cannot mutate something inside an RC, and we need to do based on [this](https://doc.rust-lang.org/std/cell/index.html#introducing-mutability-inside-of-something-immutable). I can create a PR and test it, then let you know.
