### ISSUE TITLE
Commits and tags not signed anymore?

### ISSUE THREAD

**Issue by Antiz96** [danyspin97/wpaperd#102]
Hi,

All commits and tags used to be signed with the `1733BCAC9AF70936` OpenPGP key.
As such, I made the Arch Linux package for wpaperd to verify that the downloaded source (in that case, git tags) are indeed [signed with that key](https://gitlab.archlinux.org/archlinux/packaging/packages/wpaperd/-/blob/main/PKGBUILD?ref_type=heads#L13-15).

However, I just noticed that the [recent commits](https://github.com/danyspin97/wpaperd/commits/main/) and the [latest tag](https://github.com/danyspin97/wpaperd/tags) are not signed anymore.  
Is that expected? If so, should I just drop the signature verification from the Arch Linux package side?

Thanks in advance :)

**Comment by Antiz96** [comment]
> Hello @Antiz96, thank you for maintaining the Arch Linux package :)
> 

You're welcome, thanks for the great work on `wpaperd` :)

> My bad, I just switched from git to [jujutsu](https://martinvonz.github.io/jj/latest/) and didn't enable the signing on the latter. I'll continue to use '1733BCAC9AF70936' key to sign all commits and tags going forward. Is it an issue if `1.1.0` tag is not signed? If it is, I'll create a new one right away.

Thanks for the quick reply! 
Re-creating the `1.1.0` tag could eventually be an issue for other distros that potentially packaged it already. If creating a new signed `1.1.1` tag (for instance) is a possibility, that's fine. Otherwise I can just disable the signature verification until the next tag if you prefer ;)

Let me know :)

**Comment by danyspin97** [comment]
Hi @Antiz96 ! I waited just a bit before the new release and I got a couple of new commits in :) The new tag 1.1.1 has been released and properly signed. Thank you again!

**Comment by Antiz96** [comment]
Alright, thanks a lot! :)
