### ISSUE TITLE
Image rotation on transformed displays in Niri (wlroots based twm) not working

### ISSUE THREAD

**Issue by aserowy** [danyspin97/wpaperd#103]
Heho,

new to wpaperd and loving it so far. Except that the rotated monitor i am using shows a rotated image (as if it isnt rotated at all).

Im still on wpaperd 1.0.1. Using [Niri](https://github.com/YaLTeR/niri) and would love to get this working. Can you please give me a short hint, where i should start? Or is it a missing feature on niris side (swww is working without further config)?

Kind regards
Alexander

**Comment by danyspin97** [comment]
Hello @aserowy and thank you for the issue! 

Unfortunately, rotated monitors are broken for 1.0.1, but they should have been fixed in 1.1.0. Can you please try with the latter and see if it fixes your issue? Thanks! 

P. S. Niri is a really cool window manager, I was trying it last week :)

**Comment by aserowy** [comment]
I will get back as soon 1.1. is merged in nixpkgs.
And yeah, started with niri and cannot go back (even to hyprland) :D

**Comment by aserowy** [comment]
Works fine with 1.1.1!

Tyvm
