### ISSUE TITLE
Add IPC to get info and control wpaperd daemon

### ISSUE THREAD

**Issue by danyspin97** [danyspin97/wpaperd#12]
The IPC is needed to change the current wallpaper and to get the information about the current ones.

**Comment by 1995parham** [comment]
What do you think about using TCP socket for IPC? wpaperd listens on specific port which is configurable with config file and the wpaperd-cli use it for gathering information or changing the wallpaper?

**Comment by danyspin97** [comment]
I would use a unix socket since it's slightly easier to handle and I don't think there is any need to control wpaperd remotely. What do you think?

**Comment by 1995parham** [comment]
Yes, Unix socket is better for inner system communication. I will try to create a PR for this.

**Comment by danyspin97** [comment]
I'd wait for wayland-rs 0.30 to come out, because wpaperd will be refactored to use it.

**Comment by murlakatamenka** [comment]
I'd say the easiest way would be to use signals, like show/hide on `SIGUSR2` and reload (pick another wallpaper) on `SIGUSR2`. This is how `waybar` works.

**Comment by danyspin97** [comment]
Using signals is not really user friendly, I personally prefer to have an IPC. In this case wpaperd could have more granular control and an IPC allows that.

An IPC along with a control cli command (`wpaperctl`) have been added in add9072, closing this issue.

**Comment by murlakatamenka** [comment]
> Using signals is not really user friendly, I personally prefer to have an IPC. In this case wpaperd could have more granular control and an IPC allows that.

signals are good for something really simple, works fine for a few commands. As for user-friendliness, binding `pgrep`/`killall` command with a hotkey is very easy in sway or Hyprland, so can't agree on that point.

Anyway, thanks a lot for working on this feature :+1:
