### ISSUE TITLE
2 different images on 2 different screens/monitors

### ISSUE THREAD

**Issue by mathiasbolle** [danyspin97/wpaperd#19]
My configuration file is the following:
[default]
path = "/home/mathias/Pictures/desktop_wallpapers"
duration = "30m"
where the path contains 2 images.
but the result is that my laptop screen and monitor screen got 2 different images.
Is this normal or is there a way to 'sync' them that they display the same image?

**Comment by danyspin97** [comment]
Hi and thank you for your question.

Each output without an explicit section will fallback on the `[default]` configuration. So each of your 2 monitors will pick a random image from the same path.

Currently there is no way to synchronize different monitors to share the same picture. The implementation is being discussed in #17, so I'll close this issue in favor of the other one.

**Comment by mathiasbolle** [comment]
Thank you for your quick response and afford for developing this application!
