### ISSUE TITLE
Opening the image fails with insufficient memory

### ISSUE THREAD

**Issue by pm4rcin** [danyspin97/wpaperd#21]
Hi, I have a problem that 2 wallpapers don't want to be set by wpaperd. Also I have lots of files in `.local/state/wpaperd` with following content:
```bash
WARN [calloop::sources::ping] [calloop] Failed to write a ping: EPIPE
```
[log](https://gist.github.com/pm4rcin/15ad54e4b24e71c54917b2c2128c5a25)
Maybe the files are problematic but I don't know since insufficient memory is not helpful because it is able to process much bigger files.
Wallpapers:
[1](https://www.mediafire.com/view/ksjeymcm6hrfkdp/c3a88b3ed4bc2c587acd038072089993fd53fbbd.png/file)
[2](https://www.mediafire.com/view/delb9pg7lnuujc5/CP77-VDay-1920x1080_EN.png/file)
OS: Arch 5.19.12
WM: dwl
wlroots 0.15.1
wpaperd 0.2.0
CPU: Ryzen 5 4600H
GPU: Integrated + Nvidia GTX 1650 (515.76)

**Comment by danyspin97** [comment]
Hi @pm4rcin and thank you for the report. This is a bug in the image crate, tracked in https://github.com/image-rs/image/issues/1788 . We have to wait until it is fixed, unfortunately.

**Comment by pm4rcin** [comment]
There's a new release available. Could you update the crate and provide hotfix release?

**Comment by danyspin97** [comment]
I have just tried the new image release and the issue hasn't been fixed. I have also updated the upstream issue.

**Comment by pm4rcin** [comment]
Is output exactly the same?

**Comment by danyspin97** [comment]
Yea, it is, unfortunately. It still fails in wpaperd and also in the reproducer in the linked issue.

**Comment by pm4rcin** [comment]
@danyspin97 looks like it was fixed in the meantime https://github.com/image-rs/image-png/commit/8a499d93e3528c67f93443c6644e734dbe20168f. Could you check? :)

**Comment by danyspin97** [comment]
Hello @pm4rcin! Yes, it has been fixed upstream, and I can confirm that wpaperd now can load the images you shared 😄 .

**Comment by pm4rcin** [comment]
Took over a year but nice. @danyspin97 what about new release since it was a long time since last and it would be nice to provide program that has fixed issue. If you don't want a full release maybe just update dependency and create some minor release?

**Comment by danyspin97** [comment]
@pm4rcin Release 1.0 is coming next month :) I have finished all the big features and now I am just polishing everything. If by then I haven't been able to complete everything, I'll just create a minor release with this fix and a couple of others as you suggested.
