### ISSUE TITLE
Consider allowing `.toml` as the config file suffix

### ISSUE THREAD

**Issue by CobaltCause** [danyspin97/wpaperd#25]
This would be nice so that editors don't need special configuration in order for syntax highlighting to work.

**Comment by danyspin97** [comment]
That's a nice idea and we are still on time before the next release to implement this.

**Comment by danyspin97** [comment]
This is issue has been fixed in `0.3.0`. The name of the file `output.conf` have been changed to `wallpaper.toml`. The old file name will be supported for a while though.
