### ISSUE TITLE
Rapid switching when certain programs open

### ISSUE THREAD

**Issue by Mrfiregem** [danyspin97/wpaperd#3]
When using programs like `swaylock` or `nwg-drawer`, or receiving a notification in `mako`, the wallpaper will switch twice, once when opening, and once when closing the app or notification. This is on river 0.1.2, which uses wlroots 0.15.

I also tried to see if it happened on sway 1.7 which also uses the newest wlroots, but the image doesn't show up regardless of if the path is a folder or file.

**Comment by danyspin97** [comment]
> When using programs like swaylock or nwg-drawer, or receiving a notification in mako, the wallpaper will switch twice, once when opening, and once when closing the app or notification. This is on river 0.1.2, which uses wlroots 0.15.

I have just changed system and I am experiencing the same bug on sway 1.17. I'll add some more robust check for the timer.

> I also tried to see if it happened on sway 1.7 which also uses the newest wlroots, but the image doesn't show up regardless of if the path is a folder or file.

Can you please open a new bug for this issue? Thank you!

**Comment by danyspin97** [comment]
This issue has been fixed by 588dfafd1513c954f6dee40230ecabff1b527383.
