### ISSUE TITLE
Not installing wpapercli from AUR wpaperd-git

### ISSUE THREAD

**Issue by CharlesAttend** [danyspin97/wpaperd#33]
Hello 👋
Thank you for your wallpaper utility, I really like to have a random wallpaper everyday and wpaper is perfect for this. 

However, to get pywal to work automaticly, I need to get the current wallpaper. I just saw that you recently added wpapercli which seem to be capable of that ! 

But even after installing from AUR using `yay -S wpaperd-git` I cannot find the command in my system. Do I need to build directly from source ? Isn't what yay do ? 

Thank you for your answer 🙏

**Comment by CharlesAttend** [comment]
I'll close the issue when the PR will be pushed 😉

**Comment by danyspin97** [comment]
Unfortunately I don't think I can update it directly but we have to wait for the package maintainer to do so :/ . Maybe it would be faster to use wpaperd from the repository in the meanwhile.

**Comment by CharlesAttend** [comment]
Thank you, I build it manualy so :D
