### ISSUE TITLE
[FEATURE] Previous wallpaper

### ISSUE THREAD

**Issue by Rolv-Apneseth** [danyspin97/wpaperd#34]
I would like this feature for my own use, and I could contribute some code if I could get some guidance? I want to be able to go to the previously set wallpaper, and maybe keep going back through wallpapers if it has changed multiple times. What would be the best way to achieve this?

My current idea is that when the `files` vec is created, shuffle and store it, then the image could just be set by the index. Subsequent calls would increase the index by 1 and a call with a new `--previous` would go back 1? Probably gonna be a lot more to it than that but what would you think about this?

This could probably also be relevant for #5  as the list could also not be shuffled.

**Comment by danyspin97** [comment]
Hello @Rolv-Apneseth! Yea, this feature could be a good addition to wpaperd.


> My current idea is that when the files vec is created, shuffle and store it, then the image could just be set by the index. Subsequent calls would increase the index by 1 and a call with a new --previous would go back 1? Probably gonna be a lot more to it than that but what would you think about this?

I like this solution, calculating the wallpapers beforehand is straightforward at start. However, since the configuration isn't static, it means that it would be recalculated every time the config changes, and, though it would be doable, I am not sure it would be straightforward.

I am thinking more of leaving the current selection as it is, and changing `current_img` field in Surface into a Vec. The new selected image would get added there, and `previous-wallpaper` would just set the previous. If the current index is not the last one of this Vec, we would overwrite the next position and move from there. What do you think of this solution?

> This could probably also be relevant for https://github.com/danyspin97/wpaperd/issues/5 as the list could also not be shuffled.

I think that adding a new ordering method for that could also be a solution as well.

I am here if you need any more guidance :)

**Comment by Rolv-Apneseth** [comment]
> I am thinking more of leaving the current selection as it is, and changing `current_img` field in Surface into a Vec. The new selected image would get added there, and `previous-wallpaper` would just set the previous. If the current index is not the last one of this Vec, we would overwrite the next position and move from there. What do you think of this solution?

I'd say this is probably better, thanks. So to clarify, it would go:
1. new image is set, and added to the end of the vec (assuming some index variable will still be useful here?)
2. if previous is called, the previous image in that vec is set as the current

Then calling `wpaperd` should just go back to the original image set in step 1 and continue from there? Let me know if it's wrong but calling `wpaperd` by itself is basically what I've been using for my `next wallpaper` keybinding lol

I'll have a look over it today and probably the next couple of days when I have free time, and come back here if I need help, thanks.

**Comment by Rolv-Apneseth** [comment]
> I have added a cli control command in the latest git version. You can run `wpaperctl next-wallpaper` to switch wallpaper without killing and starting wpaperd. In this case `previous-wallpaper` command would be added to ask wpaperd to go back with the index and load the image from there.

Ah ok good to know, that should work perfectly then.

**Comment by Rolv-Apneseth** [comment]
I have some quick questions about the build process:

1. Is the command `cargo install --path="."` supposed to install both the daemon and the cli? It instead gives me an error: 

    ```
    error: found a virtual manifest at `/home/rolv/repos/wpaperd/Cargo.toml` instead of a package manifest
    ```
    
    To actually install both I need to do `cargo install --path="./cli"` and the same for the daemon. 
    
2. I had an error when building the cli about `Deserialize` and `Serialize` being imported as traits rather than derives, and I fixed it  by adding this line to the `Cargo.toml`, is this fine:

    ```
    serde = { version = "1.0", features = ["derive"] }
    ```

**Comment by danyspin97** [comment]
This feature has been added, thank you for the contribution!
