### ISSUE TITLE
No wallpaper in Sway 1.7

### ISSUE THREAD

**Issue by Mrfiregem** [danyspin97/wpaperd#4]
Running the program in Sway using
- `exec wpaperd` in config
- `swaymsg exec wpaperd`
- `wpaperd`

fails to display any change to the wallpaper, though the program still runs in the background.

Originally part of #3.

**Comment by danyspin97** [comment]
Thank you for the bug report! I have added some logging in the latest commits, can you please compile from the source and run:

```bash
$ pkill wpaperd
$ RUST_LOG=trace ./target/release/wpaperd
```

It should create a log in `~/.local/state/wpaperd` which will be useful for debugging this issue.

**Comment by Mrfiregem** [comment]
The problem was between the monitor and chair 😆. When I copied over the default config file after installing sway, I left the line that set the default background. Thought it would be overridden since the line starting wpaperd was below it, but I guess not.

```sh
output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
exec wpaperd
```

**Comment by danyspin97** [comment]
I am glad that it worked fine! I will add a warning about removing `output * bg` and killing `swaybg` that might be running in the background.
