### ISSUE TITLE
Error while using the example configuration

### ISSUE THREAD

**Issue by Eckstrom13** [danyspin97/wpaperd#41]
Error:
   0: TOML parse error at line 1, column 3
   0:   |
   0: 1 | 1 [default]
   0:   |   ^
   0: expected `.`, `=`
   0:

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by danyspin97** [comment]
Hello and thank you for the report! Can you please share your configuration?
