### ISSUE TITLE
Set a specific order in which to show wallpapers

### ISSUE THREAD

**Issue by nnuel** [danyspin97/wpaperd#5]
I am looking for a method to display a clock of sorts as a wallpaper. It would be updating every five minutes, so there's 144 images for each day. Could I set a specific order with this program or could there be smarter ways to implement this.

**Comment by danyspin97** [comment]
Right now there is no way to do so when using wpaperd. You could write a script that call swaybg every five minute.
The selection mode (`ordered`, `random`) from a directory would be a good addition to wpaperd that I am looking forward to add in the future. In that case you would simply have all the images named in a sequential order.

**Comment by danyspin97** [comment]
Hello @nnuel , `sorting` has been added and allows you to put all the images in an oreded way and wpaperd will show them in the order.

I am closing this for now, please reopen it if `sorting` doesn't suffice your use case!
