### ISSUE TITLE
Terminal command to delete current image and move to next image

### ISSUE THREAD

**Issue by caniko** [danyspin97/wpaperd#51]
I am downloading a bunch of images from Unsplash, and don't have the will to manually go through each image.

It would be nice to just delete images I don't like if it shows up using some terminal command; obviously we would proceed to the next image in the sequence after the deletion.

**Comment by tbaumann** [comment]
If you run master you have a cli to request the current picture.
```
› wpaperctl all-wallpapers
DP-3: "/home/tilli/wallpapers/wallhaven-qzpjkr.png"
```

With some minor shell magic you could cut out that path and delete the file. (And advance via `wpaperctl next-wallpaper`)

**Comment by caniko** [comment]
I am on `hyprland`; what is `wpaperctl`?

**Comment by tbaumann** [comment]
Oh man, I'm sorry I was lurking in two different projects and didn't pay attention. Different project.

**Comment by caniko** [comment]
No worries, happy new year!
