### ISSUE TITLE
[Bug]: always expecting image from "/tmp/new.png" on start

### ISSUE THREAD

**Issue by leftas** [danyspin97/wpaperd#53]
Since https://github.com/danyspin97/wpaperd/commit/ce4337ecea67958e7c3f10d3c8bd34abe44b8fd8#diff-024866410d3fba80dd37f0bfe3647f70f2e7043a78247188f9eefcae301be2ccR49 commit, wpaperd expects image residing in /tmp named "new.png".

Although I can submit a PR, but I am not sure about two things: 
  - Does the application now always expect to have some default image on start (or at least you want to move into that direction). Or was this unintentionally left because of testing purposes (but from what I am seeing in CL, this should be true) ? 
  - If your answer was yes for the first question, would supplementing a directory and then searching an image in that directory would suffice ? Because, I suppose, image_path should be taken from new (which does not exist in a code base rn) method, which would search through directory and return random/first or whichever photo - essentially what `get_image` does.

**Comment by danyspin97** [comment]
Hello @leftas!

>  wpaperd expects image residing in /tmp named "new.png".

Yes, the image "new.png" was a placeholder while I worked on other things.

> Does the application now always expect to have some default image on start (or at least you want to move into that direction). 

The idea is to have a proper fade in effect from the display manager. Let's say that the display manager uses an image saved in `/tmp/my_login_image.png`, I want wpaperd to load that image and then transition to the image chosen by the user, i.e. returned by `get_image`. This should be an option in both the configuration and the cli arguments, hence why a placeholder was put in place... at the same time I needed an image to load and transition into. I'll use a single black pixel (maybe even allowing the user to choose the color) if no starting image was set.

Apologies if this was breaking your setup, working on transitions and background mode has taken most of my time and I wasn't able to implement this feature yet.

How this idea sound? Potentially, I should look into a way to interact with the DM to get the current image used but I am not sure that would be any...

**Comment by leftas** [comment]
Hi @danyspin97!

I see, that is what I suspected, haha. Well the idea is nice, it would be really neat to have that. However, I want to make sure two things, so there should be an option in CLI and config files to specify starting image, right? If so, you intend on having only one image and not a directory of them? So essentially, what this code is now lacking (for short-term) having an argument which accepts starting image(s) from which it would transition into your specified images (from get_image). Because now the question, whether you want me to make a CL or you will by yourself, hahaha. 

Regarding the breaking, no worries - it is not something crucial that wouldn't start my system, hahaha!

Well, although, I support the idea, I find it a bit tedious to support in the long run especially when there is no protocol :(. However, this is your software, and I am just sharing my opinion as per your question about soundness, hahaha.

**Comment by danyspin97** [comment]
Fixed by 0cccd3b, now it automatically loads a black pixel.
