### ISSUE TITLE
Remove libxkbcommon dependency from README

### ISSUE THREAD

**Issue by unixpariah** [danyspin97/wpaperd#55]
After 0.17.0 version of sctk libxkbcommon is no longer a dependency unless feature "xkbcommon" is added

**Comment by danyspin97** [comment]
Hello @unixpariah, and thanks for opening an issue! You're right about the dependency, wpaperd doesn't depend on xkbcommon anymore.

Fixed by https://github.com/danyspin97/wpaperd/commit/8f1555cdcb559879abb357ae7cd945332ae21f5f.
