### ISSUE TITLE
Message:  called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by xaviduds** [danyspin97/wpaperd#58]
δ wpaperd
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/surface.rs:173

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Hello, when running NixOS I'm getting this error when trying to run wpaperd manually or putting it on exec-once. I couldn't get it to work in any way. I've checked the path to the images, it's correct. (just checked it again).

Why is this happening? I have home manager, this is the config:
    programs.wpaperd = {
      enable = true;
      settings = {
        any = {
          path = "/home/eduardo/notas/wallpapers/";
          sorting = "random";
          duration = "10s";
        };
      };
    };

This is the file that is created at ~/.config/wpaperd/wallpaper.toml
[any]
path = "/home/eduardo/notas/wallpapers/"
sorting = "random"
duration = "10s"

That gave me the initial error, so i tried to do it the home.file.blablabla.text way too:
      ".config/wpaperd/config.toml".text = ''
        [any]
        path = "/home/eduardo/notas/wallpapers/"
        sorting = "random"
        duration = "10s"
      '';

And it erroed that the wallpaper.toml was not found or smth, and then i did them both and got the initial error.

In my configuration.nix I have managed to install swww (which works fine), wpaperd, mesa, egl-wayland (didnt find wayland-egl), I couldn't find wayland-client on nixos search packages.

How do I fix it?

**Comment by danyspin97** [comment]
Hello @xaviduds and thanks for opening an issue!

I think this error is not related to the configuration but rather to some other part of the application. Are you running the latest version from git? Because currently https://github.com/danyspin97/wpaperd/blob/main/daemon/src/surface.rs#L173 does not contain an `unwrap`.

I am adding some more error logging and removing the unwraps, let's see if this help us finding the issue.

**Comment by xaviduds** [comment]
I believe I am:
δ wpaperd --version
wpaperd 0.3.0

I run nixos unstable and have version 0.3.0 through:
https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=wpaperd

**Comment by danyspin97** [comment]
Version 0.3.0 has been released last year and wpaperd has changed a lot since then. I will be releasing version 1.0 in the next weeks, which should work without any issue.

Can you please try the version from git in the meanwhile?

**Comment by xaviduds** [comment]
Hello, after trying a workaround i managed to get this in my hyprland configuration, that works for me:
"SUPER, W, exec, swww kill && swww-daemon & shuf -n 1 -e /home/eduardo/notas/wallpapers/* | xargs -I {} swww img {}"

**Comment by danyspin97** [comment]
Hello @xaviduds, the new release it out and fixes that issue :)
