### ISSUE TITLE
Wpaper stopped working with "unable to create an EGL context: BadMatch" error

### ISSUE THREAD

**Issue by ksiezak** [danyspin97/wpaperd#62]
As in title.

Wpaperd version: 1.0.1 installed from AUR wpaperd package. I also tested wpaperd-git with the same result.
OS: Arch Linux with ALHP x86-64-v2 repo
Compositor: Hyprland 0.39.1
HW: Old Samsung RC520 laptop with dual Intel + Nvidia graphics. Only Intel is used in Hyprland but nvidia 390 module is loaded into the kernel.

It was working previously, but I don't know which version broke it for me.

Log:

```
RUST_BACKTRACE=1 RUST_BACKTRACE=full wpaperd -v
DEBUG [smithay_client_toolkit::registry] Bound new global [49] wl_output v4
DEBUG [smithay_client_toolkit::registry] Bound new global [48] zxdg_output_manager_v1 v3
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Argb8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xrgb8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xbgr8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Abgr8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Bgr888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Rgbx4444
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Rgba4444
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Rgbx5551
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Rgba5551
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Rgb565
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xbgr2101010
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Abgr2101010
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xbgr16161616f
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Abgr16161616f
The application panicked (crashed).
Message:  unable to create an EGL context: BadMatch
Location: daemon/src/render/egl_context.rs:43

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by danyspin97** [comment]
Hello @ksiezak and thank you for the issue.

The new version of wpaperd uses openGL ES to render the image and I think it might be due to a version mismatch. Can you please run the following command and share its result?

```bash
$ glxinfo | grep "OpenGL ES profile version"
```

**Comment by ksiezak** [comment]
Sure @danyspin97 
```
$ glxinfo | grep "OpenGL ES profile version"
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 24.0.6-arch1.2.1
```

On the another computer I have version 3.2 of OpenGL ES, and it is working fine.

**Comment by danyspin97** [comment]
Oh, I see, then it's the openGL ES version 3.2 used by wpaperd that is not supported. Let's try to use openGL ES 3.0 instead. I'll add a commit asap with this change.

**Comment by danyspin97** [comment]
Apologies for the delay but I am working on having many transitions from https://gl-transitions.com/ and lowering the GLES version might cause some issues, so I am waiting until that is ready to check what might not work.

**Comment by ksiezak** [comment]
I changed wallpaper daemon to another software on that old laptop so it is no longer issue for me. If it would be burden to downgrade that GLES it can stay in current version.

I am continuing to use wpaperd on more modern PC. It is great software and lack of supporting very old hardware is understandable.
