### ISSUE TITLE
avif image cannot be loaded

### ISSUE THREAD

**Issue by Sendan4** [danyspin97/wpaperd#66]
I am using Hyprland and the latest version of wpaperd 1.0.1

according to the [readme](https://github.com/danyspin97/wpaperd/blob/main/README.md) and the link you provide about format support, avif should be supported.

I am using 8-bit lossy encoded avif images.

```bash
$ wpaperd
WARN [wpaperd::image_loader] Unsupported(UnsupportedError { format: Exact(Avif), kind: Format(Exact(Avif)) })
```

**Comment by danyspin97** [comment]
Hello @Sendan4, thank you for the report. avif feature was enabled for the image crate but it's only used for deconding. At the current moment only the library `libdav1d` can decode avif images, I have added an optional feature to fix that.

Now wpaperd supports avif images when built with `avif` feature.
