### ISSUE TITLE
Option to set the same random wallpaper to all monitors

### ISSUE THREAD

**Issue by Nairou** [danyspin97/wpaperd#74]
Being able to supply a folder and get a random wallpaper is great. However, I have two monitors, and not all wallpapers look good together. More often than not, I pick a single wallpaper to apply to both, for this reason.

Would it be possible to get an option to allow randomization, but pick the same wallpaper for both monitors?

**Comment by danyspin97** [comment]
Hello @Nairou, the option has just been added. Let me know if it works correctly!

**Comment by Nairou** [comment]
I'm on NixOS and haven't yet figured out how to make a custom build, but I appreciate the update! You work fast!
