### ISSUE TITLE
Missing transition option

### ISSUE THREAD

**Issue by zDyanTB** [danyspin97/wpaperd#75]
The project already has some effects for transitions, but no options to select one.

When it'll come?

**Comment by danyspin97** [comment]
Hello @zDyanTB !

Transition can already be selected by using the following syntax:

```
[default]
path = "~/Pictures/Wallpapers"
mode = "center"
[default.transition.hexagonalize]
```

**Comment by danyspin97** [comment]
Unfortunately, it's not documented yet as each transition has some configuration options, it will take some time to properly write it down.

**Comment by zDyanTB** [comment]
Sure! Thank you
