### ISSUE TITLE
`wpaperctl previous` not working

### ISSUE THREAD

**Issue by Unfinished632** [danyspin97/wpaperd#91]
It doesn't even print anything. Just doesn't work.

```
[any]
path = "~/wallpapers/"
duration = "5m"
sorting = "random"
mode = "center"
transition-time = 300
offset = 0.0
queue-size = 10
initial-transition = true
```

**Comment by danyspin97** [comment]
Hello @Unfinished632, thank you for the report. Does `wpaperctl next` work? Which version of wpaperd are you running?

**Comment by Unfinished632** [comment]
@danyspin97  I am running 1.0.1. `wpaperctl next` does work. And this only happens when sorting is set to random.

**Comment by danyspin97** [comment]
Can you please try with the git version?

**Comment by Unfinished632** [comment]
It works now but the previous wallpaper is seemingly random. Isn't it supposed to be in a queue?

**Comment by danyspin97** [comment]
> It works now but the previous wallpaper is seemingly random(it's supposed to be in a queue).

Yea, it's supposed to show the previous wallpapers. How many wallpapers are in the folder?

**Comment by Unfinished632** [comment]
>How many wallpapers are in the folder?

There are 7 wallpapers in the folder.

**Comment by danyspin97** [comment]
> There are 7 wallpapers in the folder.

The queue size is bigger than the number of wallpapers, so that breaks the queue. Can you please try putting `queue-size = 7`? And if it doesn't work, `queue-size = 6`. I should add a warning and an explanation in the README regarding this.

**Comment by Unfinished632** [comment]
Yup, this fixed the issue. Thanks!
