### ISSUE TITLE
transition-time not respected

### ISSUE THREAD

**Issue by guttermonk** [danyspin97/wpaperd#92]
I have the following in my `config.toml` file:
```
[default]
duration = "1m"
mode = "stretch"
sorting = "random"
transition-time = "10000"

[any]
path = "/home/guttermonk/.config/wallpapers/"
```
I assume what I have above is correct since the instructions say the default value is `300`, but I also tried `transition-time = "10000ms"` and `transition-time = 10000` with no luck.

Can anyone confirm the correct format for `transition-time` and is there a range of acceptable values?

**Comment by guttermonk** [comment]
I'm running wpaperd 1.0.1 on NixOS unstable (btw) with hyprland.

Didn't see any options to set a transition in the Wallpaper Configuration section of the readme, so I assume it's using whatever the default is.

I just tried setting my config like this:
```
[default]
duration = "1m"
mode = "stretch"
sorting = "random"
transition-time = 5000
[default.transition.stereo-viewer]

[any]
path = "/home/guttermonk/.config/wallpapers/"
```
But still seeing <1sec transitions, and no logged errors.

**Comment by gumelarme** [comment]
> I'm running wpaperd 1.0.1 on NixOS unstable (btw) with hyprland.

Same settings, in my case it also doesn't apply the chosen transition and always use fade.

**Comment by danyspin97** [comment]
wpaperd 1.0.1 contains some bugs and does not support the various transition settings. wpaperd master instead properly respect `transision-time` and `transition`. Can you please try with wpaperd master?

**Comment by guttermonk** [comment]
I pulled the nix flake for master and `transition-time` and `transition` are working as expected. Thanks for the suggestion. I'll keep using the flake for now.

**Comment by danyspin97** [comment]
Glad to know that now everything is working :)
