### ISSUE TITLE
(Feature Request) Add the status command

### ISSUE THREAD

**Issue by jerezoff** [danyspin97/wpaperd#99]
Hi! I love using `wpaperd`. I'm currently on [Hyprland](https://github.com/hyprwm/Hyprland), and I wish to add wallpaper status to [Waybar](https://github.com/Alexays/Waybar).

### What do I want?
I'd like to write a script that wraps command output into an interactive button inside Waybar.

### What do I suggest?
Adding a command (e.g. `wpaperctl status`) that returns the current state of the daemon (playing/paused/stopped).

P.S. I don’t know if there's another way to achieve this.

**Comment by danyspin97** [comment]
This seems like a good idea, there is no way to know that currently. In addition, status will also print the remaining time of the timer.

I am currently working on it, I need to rework the timer a bit because it wasn't giving me the correct time.

**Comment by danyspin97** [comment]
It's done, I just need to print the time properly in a user-friendly way.
